class_name BrickPalette

## The standard part palette: one place that decides what a part is.
##
## A **part** is what a player picks and what a recipe names -- "2x4 brick".
## An **archetype** is what the extension bakes, and there is one per
## orientation, because rotation is not a runtime feature (Docs/Status.md
## limitation 14). This table lists PARTS; `bake()` expands each into the
## archetypes it needs and hands back both maps.
##
## That split is the point. Hand-writing `brick_2x4_x` and `brick_2x4_z` as two
## table entries leaked a runtime representation into the authoring layer:
## adding a part meant remembering to add it twice, a square part could pick up
## a meaningless suffix, and build mode would have had to show a player two
## entries for one brick. The duplication belongs in the generator, where it is
## free, and Docs/BuildMode.md section 3's 8-orientation bake is the same
## generator with flips added.
##
## Why not put rotation on `Block` instead and have one archetype? Because the
## cost lands in the wrong place. Occupancy claiming, `for_each_neighbour`,
## `joint_exists`, the face bake and the collision transform would each have to
## rotate, and the first three are the hot path -- `for_each_neighbour` runs
## four times per cascade step and a 3x lookup increase there already measured
## over 200 ms at 16.5k blocks. What it would save is archetype count, which is
## tens, in the low MB. That is the flyweight pattern working: bake the variants,
## keep the runtime dumb.
##
## -------------------------------------------------------------------------
## Proportions -- the thing that has to stay true
## -------------------------------------------------------------------------
##
## Print scale (spec section 3) and game scale (Plan D6) are the same system at
## two sizes, and the ratios are EXACT in both:
##
##            print      game       ratio
##   stud     8.0 mm     0.35 m     x 43.75
##   plate    3.2 mm     0.14 m     x 43.75
##   brick    9.6 mm     0.42 m     x 43.75   (3 plates)
##
##   plate / stud = 0.4    in both
##   brick / stud = 1.2    in both
##
## A part is described entirely by integers, and its real proportions follow
## from the grid rather than from anything written here. `tools/palette_probe.gd`
## asserts all of it.
##
## -------------------------------------------------------------------------
## Naming
## -------------------------------------------------------------------------
##
## A part is `<family>_<W>x<L>` with W <= L always, so a 1x4 is never a 4x1.
## An archetype adds an ORIENTATION suffix:
##
##   `_x` / `_z`  the axis the LONG side runs along. A square part has neither.
##   `_i`         inverted: 180 degrees about X, so its studs point DOWN.
##
##   part  brick_2x4  ->  brick_2x4_x    Vector3i(4, 3, 2)   studs up
##                        brick_2x4_z    Vector3i(2, 3, 4)   studs up
##                        brick_2x4_x_i  Vector3i(4, 3, 2)   studs down
##                        brick_2x4_z_i  Vector3i(2, 3, 4)   studs down
##   part  brick_2x2  ->  brick_2x2, brick_2x2_i
##
## Those eight grid-legal orientations (4 yaw x 2 flip) are generated by
## `BrickWorld.bake_variant`, which dedupes -- a square footprint yawed 180
## degrees is the part it already was, so most parts resolve to two or four
## archetypes rather than eight. What is NOT here is a sideways brick: it is not
## one of the eight and cannot be, because rotating 90 degrees about X or Z
## swaps a stud axis with the plate axis (Docs/BuildMode.md section 2.1).
##
## -------------------------------------------------------------------------
## Studs
## -------------------------------------------------------------------------
##
## Plates and bricks carry studs on top and sockets underneath, so anything can
## be built on them. **Tiles are studless**: solid, one plate tall, sockets
## underneath, nothing on top. A thing rests on a tile and does not clip to it,
## which is a structural fact the connectivity graph reads rather than a finish
## -- and it is the only reason a tile is not a plate by another name.
##
## A studless BRICK (a wall cap) is the obvious next one and is a single table
## row whenever it is wanted.
##
## None of this is visible yet either way: stud GEOMETRY is M5 (Plan D4). A stud
## mask today is a structural fact the connectivity graph reads, not something
## you can see.

## Grid, mirrored from gdextension/brick/src/brick_grid.h. GDScript cannot read
## those constants, so the probe asserts the two agree rather than trusting it.
const STUD_M := 0.35
const PLATE_M := 0.14
const PLATES_PER_BRICK := 3

## Print scale, spec section 3.
const STUD_MM := 8.0
const PLATE_MM := 3.2

## Grams per grid cell, where a cell is 1 stud x 1 plate x 1 stud.
##
## Anchored on the real thing: a 2x4 brick is 2 x 4 x 3 = 24 cells and weighs
## about 2.4 g (it is hollow -- solid ABS at that volume would be over 5 g).
## Every other part follows from its cell count, so relative masses are right by
## construction and a plate is exactly a third of the brick it matches.
##
## This is print-scale mass. Docs/BrickFailure.md section 4.5 converts to game
## scale, in one place.
const MASS_PER_CELL := 0.1


# ---------------------------------------------------------------------------
# The parts. Vector3i is the CANONICAL footprint (W studs, H plates, L studs)
# with W <= L. Orientation is generated, never written here.
#
# H = 1 is a plate, H = 3 is a brick.
# ---------------------------------------------------------------------------

const _PARTS := {
	# --- plates, one plate tall -----------------------------------------
	"plate_1x1": Vector3i(1, 1, 1),   # one stud. the smallest part there is
	"plate_1x2": Vector3i(1, 1, 2),
	"plate_1x4": Vector3i(1, 1, 4),
	"plate_1x6": Vector3i(1, 1, 6),
	"plate_2x2": Vector3i(2, 1, 2),
	"plate_2x4": Vector3i(2, 1, 4),
	"plate_4x4": Vector3i(4, 1, 4),
	## A floor panel. One of these covers what a hundred 1x1 plates would, and
	## floors were 75% of every block in a building -- 30,855 plate_4x4 of a
	## 50,535-block tower -- so the size of the floor unit is the single biggest
	## number in the whole brick budget.
	"plate_10x10": Vector3i(10, 1, 10),

	# --- columns, four bricks tall --------------------------------------
	# One block each rather than four stacked bricks, because a column is a
	# column: nothing is ever going to break it in the middle that would not
	# also break it whole, and four blocks would cost four of everything.
	#
	# Twelve plates is exactly four courses, which is exactly the gap between
	# one floor and the next -- so a column stands on the floor below and the
	# floor above stands on it.
	"column_1x1": Vector3i(1, 12, 1),
	"column_2x2": Vector3i(2, 12, 2),

	# --- bricks, three plates tall --------------------------------------
	"brick_1x1": Vector3i(1, 3, 1),   # one stud, full height
	"brick_1x2": Vector3i(1, 3, 2),
	"brick_1x4": Vector3i(1, 3, 4),
	"brick_1x6": Vector3i(1, 3, 6),
	"brick_2x2": Vector3i(2, 3, 2),
	"brick_2x4": Vector3i(2, 3, 4),

	# --- tiles, a plate with a smooth top -------------------------------
	# Solid, one plate tall, sockets underneath and NO studs on top: things
	# rest on a tile and nothing clips to it. That is a structural property
	# the connectivity graph reads, not a finish -- and it is why a tile is
	# not just a plate by another name.
	"tile_1x1": Vector3i(1, 1, 1),
	"tile_1x2": Vector3i(1, 1, 2),
	"tile_1x4": Vector3i(1, 1, 4),
	"tile_1x6": Vector3i(1, 1, 6),
	"tile_2x2": Vector3i(2, 1, 2),
	"tile_2x4": Vector3i(2, 1, 4),
	"tile_4x4": Vector3i(4, 1, 4),

	# --- brackets, a brick with studs on one SIDE ------------------------
	# The part that makes sideways building reachable. A rotated frame steps
	# its build plane by one plate (2 ticks) while upright brick faces sit at
	# stud boundaries (multiples of 5), so a frame at a fixed origin can only
	# meet every second stud. A bracket names the exact plane to put a frame
	# on, and the parity problem goes away.
	#
	# Studs face the part's +X: down its long side, one per stud of length.
	"bracket_1x1": Vector3i(1, 3, 1),
	"bracket_1x2": Vector3i(1, 3, 2),
	"bracket_1x4": Vector3i(1, 3, 4),
	"bracket_2x2": Vector3i(2, 3, 2),
}


## Bake the palette. Returns archetype name -> archetype id.
##
## Each part is baked ONCE in its canonical orientation, and every other
## orientation comes from `bake_variant`, which transforms the cell mask and the
## face masks together and dedupes against what is already baked. That is why
## the returned dictionary can map several names to the same id: a square part
## has one shape whichever way you yaw it.
static func bake(world: BrickWorld) -> Dictionary:
	var out := {}
	for part in _PARTS:
		var size: Vector3i = _PARTS[part]
		var base := -1
		if has_studs(part):
			base = world.bake_archetype(part + "#base", size, mass_of(size))
		else:
			# Studless: solid box, sockets all the way across the underside,
			# nothing on top.
			base = world.bake_faced_archetype(part + "#base", size, mass_of(size),
					PackedByteArray(), _fill(size.x * size.z, FACE_NONE),
					_fill(size.x * size.z, FACE_SOCKET))
		if base < 0:
			push_error("BrickPalette: '%s' failed to bake" % part)
			continue
		if is_bracket(part):
			world.set_side_studs(base, _side_studs_for(size))
		for name in variants_of(part):
			var o := orientation_of(name)
			var id := world.bake_variant(base, name, o.x, o.y != 0)
			if id < 0:
				push_error("BrickPalette: '%s' failed to orient" % name)
			out[name] = id
	return out


## Face values, mirroring `brick::Face` in brick_types.h.
const FACE_NONE := 0
const FACE_STUD := 1
const FACE_SOCKET := 2


## Does this part carry studs on top in its canonical orientation? Everything
## but a tile does.
static func has_studs(part: String) -> bool:
	return not part.begins_with("tile_")


## A bracket also carries studs on one lateral face.
static func is_bracket(part: String) -> bool:
	return part.begins_with("bracket_")


## Side studs down the part's LONG side (+X in the canonical W x H x L), one per
## stud of its length: a 1x4 bracket has four, in a row.
##
## One per column, not one per cell of the face. A brick is three plates tall
## and a stud is one stud wide, so a column holds exactly one real stud; the
## first version put one on every plate row -- three stacked half-overlapping
## studs a column -- and on the short END face, which is not where a bracket
## has them. Each is recorded on the bottom plate row; where it actually sits
## (a stud's width up from the bottom, so a part on it stands flush with the
## bracket's own base) is the workshop's to draw and snap to.
##
## Six ints each: the cell they sit on, then the outward normal. The extension
## rotates both with the part, so every orientation of a bracket gets its studs
## facing the right way without any of this being written twice.
static func _side_studs_for(size: Vector3i) -> PackedInt32Array:
	var out := PackedInt32Array()
	var x := size.x - 1
	for z in size.z:
		# push_back one at a time: PackedInt32Array.append_array wants
		# another PackedInt32Array, and handing it an untyped Array
		# literal silently appends nothing.
		out.push_back(x)
		out.push_back(0)
		out.push_back(z)
		out.push_back(1)
		out.push_back(0)
		out.push_back(0)
	return out


## The parts a player picks from. Build mode shows these, not archetypes.
static func parts() -> Array:
	return _PARTS.keys()


## Canonical footprint of a part, (W, H, L) with W <= L.
static func part_size(part: String) -> Vector3i:
	return _PARTS.get(part, Vector3i.ZERO)


## True when a part's footprint is square, so rotating it changes nothing.
static func is_square(part: String) -> bool:
	var s: Vector3i = _PARTS.get(part, Vector3i.ZERO)
	return s.x == s.z


## Archetype names for a part, in every orientation it has: the axis variants
## (one if square, two otherwise) each in upright and inverted form.
##
## `_x` is the orientation whose LONG side runs along world X; `_i` is inverted.
static func variants_of(part: String) -> Array:
	if not _PARTS.has(part):
		return []
	var axes: Array = [part] if is_square(part) else [part + "_x", part + "_z"]
	var out := []
	for a in axes:
		out.append(a)
		out.append(a + "_i")
	return out


## The (yaw, flip) an archetype name asks for. yaw is quarter turns about +Y.
##
## The canonical part is long-on-Z, so `_z` is yaw 0 and `_x` is yaw 1.
static func orientation_of(name: String) -> Vector2i:
	var flip := 0
	var n := name
	if n.ends_with("_i"):
		flip = 1
		n = n.substr(0, n.length() - 2)
	var yaw := 1 if n.ends_with("_x") else 0
	return Vector2i(yaw, flip)


## True when this archetype name is the inverted form of its part.
static func is_inverted(name: String) -> bool:
	return name.ends_with("_i")


## Every archetype name the palette bakes.
static func names() -> Array:
	var out := []
	for part in _PARTS:
		out.append_array(variants_of(part))
	return out


## Footprint of an ARCHETYPE, resolving the orientation suffix. Vector3i.ZERO
## if the name is not one the palette bakes.
##
## A flip leaves every extent unchanged (that is exactly why it is grid-legal),
## so only the axis suffix changes the size.
static func size_of(name: String) -> Vector3i:
	var n := name
	if n.ends_with("_i"):
		n = n.substr(0, n.length() - 2)
	if _PARTS.has(n):
		return _PARTS[n]  # square part, no axis suffix
	var cut := n.rfind("_")
	if cut < 0:
		return Vector3i.ZERO
	var part := n.substr(0, cut)
	var axis := n.substr(cut + 1)
	var s: Vector3i = _PARTS.get(part, Vector3i.ZERO)
	if s == Vector3i.ZERO or is_square(part):
		return Vector3i.ZERO  # a square part must not carry an axis suffix
	# Canonical is long-on-Z. The _x variant swaps the two stud axes.
	return Vector3i(s.z, s.y, s.x) if axis == "x" else s


## The part a variant name belongs to, or "" if it is not one.
static func part_of(name: String) -> String:
	var n := name
	if n.ends_with("_i"):
		n = n.substr(0, n.length() - 2)
	if _PARTS.has(n):
		return n
	var cut := n.rfind("_")
	if cut < 0:
		return ""
	var part := n.substr(0, cut)
	return part if _PARTS.has(part) and not is_square(part) else ""


## Grams for a box part of this size, at print scale.
static func mass_of(size: Vector3i) -> float:
	return size.x * size.y * size.z * MASS_PER_CELL


## What a part measures in metres in game. Purely derived -- here so a UI can
## show it without re-deriving the grid.
static func extents_m(size: Vector3i) -> Vector3:
	return Vector3(size.x * STUD_M, size.y * PLATE_M, size.z * STUD_M)


## What the same part measures in mm on the print bed, at 1:1 (spec section 3).
static func extents_mm(size: Vector3i) -> Vector3:
	return Vector3(size.x * STUD_MM, size.y * PLATE_MM, size.z * STUD_MM)


static func _fill(n: int, v: int) -> PackedByteArray:
	var a := PackedByteArray()
	a.resize(n)
	a.fill(v)
	return a
