class_name BrickPalette

## The standard part palette: one place that decides what a part is.
##
## A **part** is what a player picks and what a recipe names -- "2x4 brick".
## An **archetype** is what the extension bakes, and there is one per
## orientation, because rotation is not a runtime feature (Docs/Status.md
## limitation 14). This table lists PARTS; `bake()` expands each into the
## archetypes it needs and hands back both maps.
##
## That split is the point. Hand-writing `brick_2x4_x` and `brick_2x4_z` as two
## table entries leaked a runtime representation into the authoring layer:
## adding a part meant remembering to add it twice, a square part could pick up
## a meaningless suffix, and build mode would have had to show a player two
## entries for one brick. The duplication belongs in the generator, where it is
## free, and Docs/BuildMode.md section 3's 8-orientation bake is the same
## generator with flips added.
##
## Why not put rotation on `Block` instead and have one archetype? Because the
## cost lands in the wrong place. Occupancy claiming, `for_each_neighbour`,
## `joint_exists`, the face bake and the collision transform would each have to
## rotate, and the first three are the hot path -- `for_each_neighbour` runs
## four times per cascade step and a 3x lookup increase there already measured
## over 200 ms at 16.5k blocks. What it would save is archetype count, which is
## tens, in the low MB. That is the flyweight pattern working: bake the variants,
## keep the runtime dumb.
##
## -------------------------------------------------------------------------
## Proportions -- the thing that has to stay true
## -------------------------------------------------------------------------
##
## Print scale (spec section 3) and game scale (Plan D6) are the same system at
## two sizes, and the ratios are EXACT in both:
##
##            print      game       ratio
##   stud     8.0 mm     0.35 m     x 43.75
##   plate    3.2 mm     0.14 m     x 43.75
##   brick    9.6 mm     0.42 m     x 43.75   (3 plates)
##
##   plate / stud = 0.4    in both
##   brick / stud = 1.2    in both
##
## A part is described entirely by integers, and its real proportions follow
## from the grid rather than from anything written here. `tools/palette_probe.gd`
## asserts all of it.
##
## -------------------------------------------------------------------------
## Naming
## -------------------------------------------------------------------------
##
## A part is `<family>_<W>x<L>` with W <= L always, so a 1x4 is never a 4x1.
## An archetype adds an ORIENTATION suffix:
##
##   `_x` / `_z`  the axis the LONG side runs along. A square part has neither.
##   `_i`         inverted: 180 degrees about X, so its studs point DOWN.
##
##   part  brick_2x4  ->  brick_2x4_x    Vector3i(4, 3, 2)   studs up
##                        brick_2x4_z    Vector3i(2, 3, 4)   studs up
##                        brick_2x4_x_i  Vector3i(4, 3, 2)   studs down
##                        brick_2x4_z_i  Vector3i(2, 3, 4)   studs down
##   part  brick_2x2  ->  brick_2x2, brick_2x2_i
##
## Those eight grid-legal orientations (4 yaw x 2 flip) are generated by
## `BrickWorld.bake_variant`, which dedupes -- a square footprint yawed 180
## degrees is the part it already was, so most parts resolve to two or four
## archetypes rather than eight. What is NOT here is a sideways brick: it is not
## one of the eight and cannot be, because rotating 90 degrees about X or Z
## swaps a stud axis with the plate axis (Docs/BuildMode.md section 2.1).
##
## -------------------------------------------------------------------------
## Studs
## -------------------------------------------------------------------------
##
## Plates and bricks carry studs on top and sockets underneath, so anything can
## be built on them. **Tiles are studless**: solid, one plate tall, sockets
## underneath, nothing on top. A thing rests on a tile and does not clip to it,
## which is a structural fact the connectivity graph reads rather than a finish
## -- and it is the only reason a tile is not a plate by another name.
##
## A studless BRICK (a wall cap) is the obvious next one and is a single table
## row whenever it is wanted.
##
## None of this is visible yet either way: stud GEOMETRY is M5 (Plan D4). A stud
## mask today is a structural fact the connectivity graph reads, not something
## you can see.

## Grid, mirrored from gdextension/brick/src/brick_grid.h. GDScript cannot read
## those constants, so the probe asserts the two agree rather than trusting it.
const STUD_M := 0.35
const PLATE_M := 0.14
const PLATES_PER_BRICK := 3

## Print scale, spec section 3.
const STUD_MM := 8.0
const PLATE_MM := 3.2

## Grams per grid cell, where a cell is 1 stud x 1 plate x 1 stud.
##
## Anchored on the real thing: a 2x4 brick is 2 x 4 x 3 = 24 cells and weighs
## about 2.4 g (it is hollow -- solid ABS at that volume would be over 5 g).
## Every other part follows from its cell count, so relative masses are right by
## construction and a plate is exactly a third of the brick it matches.
##
## This is print-scale mass. Docs/BrickFailure.md section 4.5 converts to game
## scale, in one place.
const MASS_PER_CELL := 0.1


# ---------------------------------------------------------------------------
# The parts. Vector3i is the CANONICAL footprint (W studs, H plates, L studs)
# with W <= L. Orientation is generated, never written here.
#
# H = 1 is a plate, H = 3 is a brick.
# ---------------------------------------------------------------------------

const _PARTS := {
	# --- plates, one plate tall -----------------------------------------
	"plate_1x1": Vector3i(1, 1, 1),   # one stud. the smallest part there is
	"plate_1x2": Vector3i(1, 1, 2),
	"plate_1x4": Vector3i(1, 1, 4),
	"plate_1x6": Vector3i(1, 1, 6),
	"plate_2x2": Vector3i(2, 1, 2),
	"plate_2x4": Vector3i(2, 1, 4),
	"plate_4x4": Vector3i(4, 1, 4),
	## A floor panel. One of these covers what a hundred 1x1 plates would, and
	## floors were 75% of every block in a building -- 30,855 plate_4x4 of a
	## 50,535-block tower -- so the size of the floor unit is the single biggest
	## number in the whole brick budget.
	"plate_10x10": Vector3i(10, 1, 10),

	# --- columns, six bricks tall ---------------------------------------
	# One block each rather than six stacked bricks, because a column is a
	# column: nothing is ever going to break it in the middle that would not
	# also break it whole, and six blocks would cost six of everything.
	#
	# Eighteen plates is exactly six courses (TowerRecipe.COURSES_PER_FLOOR),
	# which is exactly the gap between one floor and the next -- so a column
	# stands on the floor below and the floor above stands on it.
	# tools/scale_probe.gd fails if the two ever disagree.
	"column_1x1": Vector3i(1, 18, 1),
	"column_2x2": Vector3i(2, 18, 2),

	# --- bricks, three plates tall --------------------------------------
	"brick_1x1": Vector3i(1, 3, 1),   # one stud, full height
	"brick_1x2": Vector3i(1, 3, 2),
	"brick_1x4": Vector3i(1, 3, 4),
	"brick_1x6": Vector3i(1, 3, 6),
	"brick_2x2": Vector3i(2, 3, 2),
	"brick_2x4": Vector3i(2, 3, 4),

	# --- tiles, a plate with a smooth top -------------------------------
	# Solid, one plate tall, sockets underneath and NO studs on top: things
	# rest on a tile and nothing clips to it. That is a structural property
	# the connectivity graph reads, not a finish -- and it is why a tile is
	# not just a plate by another name.
	"tile_1x1": Vector3i(1, 1, 1),
	"tile_1x2": Vector3i(1, 1, 2),
	"tile_1x4": Vector3i(1, 1, 4),
	"tile_1x6": Vector3i(1, 1, 6),
	"tile_2x2": Vector3i(2, 1, 2),
	"tile_2x4": Vector3i(2, 1, 4),
	"tile_4x4": Vector3i(4, 1, 4),

	# --- brackets, a brick with studs on one SIDE ------------------------
	# The part that makes sideways building reachable. A rotated frame steps
	# its build plane by one plate (2 ticks) while upright brick faces sit at
	# stud boundaries (multiples of 5), so a frame at a fixed origin can only
	# meet every second stud. A bracket names the exact plane to put a frame
	# on, and the parity problem goes away.
	#
	# Studs face the part's +X: down its long side, one per stud of length.
	"bracket_1x1": Vector3i(1, 3, 1),
	"bracket_1x2": Vector3i(1, 3, 2),
	"bracket_1x4": Vector3i(1, 3, 4),
	"bracket_2x2": Vector3i(2, 3, 2),

	# --- shaped: slopes, curves, rounds, arches --------------------------
	# Not boxes. Each is drawn and collides as its shape and connects as the
	# cells that shape mostly fills (scripts/shaped_parts.gd, _SHAPED below).
	"slope_1x2": Vector3i(1, 3, 2),
	"slope_2x2": Vector3i(2, 3, 2),
	"slope_2x4": Vector3i(2, 3, 4),
	"curve_1x2": Vector3i(1, 3, 2),
	"curve_2x2": Vector3i(2, 3, 2),
	"round_1x1": Vector3i(1, 3, 1),
	"round_2x2": Vector3i(2, 3, 2),
	"arch_1x4": Vector3i(1, 3, 4),
	"arch_1x6": Vector3i(1, 3, 6),
	# A quarter-turn of spiral staircase: a round 2x2 newel and two steps of
	# two plates each. Ten studs across fills one floor panel, as the stairwell
	# does. Four of it, each turned a quarter and stacked on the last, make a
	# revolution of eight steps (ShapedParts._spiral).
	"spiral_10x10": Vector3i(10, 4, 10),
}


## How each shaped part is shaped: the ShapedParts kind and, for a slope or a
## curve, the axis it falls along in its canonical orientation. A slope falls
## toward its FRONT, the low edge at 0 along that axis.
##
## A 2x4 slope falls across its two studs, not its four, so its long side is
## the sloped face -- the real part, and the one a roof is made of.
const _SHAPED := {
	"slope_1x2": {"kind": "slope", "axis": "z"},
	"slope_2x2": {"kind": "slope", "axis": "z"},
	"slope_2x4": {"kind": "slope", "axis": "x"},
	"curve_1x2": {"kind": "curve", "axis": "z"},
	"curve_2x2": {"kind": "curve", "axis": "z"},
	"round_1x1": {"kind": "round"},
	"round_2x2": {"kind": "round"},
	"arch_1x4": {"kind": "arch"},
	"arch_1x6": {"kind": "arch"},
	# Its "front" is where its first (lower) step is; each quarter turn is a
	# different piece of the flight, so it has four orientations.
	"spiral_10x10": {"kind": "spiral", "front": Vector3i(1, 0, 0)},
}


## Bake the palette. Returns archetype name -> archetype id.
##
## Each part is baked ONCE in its canonical orientation, and every other
## orientation comes from `bake_variant`, which transforms the cell mask and the
## face masks together and dedupes against what is already baked. That is why
## the returned dictionary can map several names to the same id: a square part
## has one shape whichever way you yaw it.
static func bake(world: BrickWorld) -> Dictionary:
	var out := {}
	for part in _PARTS:
		var size: Vector3i = _PARTS[part]
		var base := -1
		if is_shaped(part):
			base = _bake_shaped(world, part, size)
		elif has_studs(part):
			base = world.bake_archetype(part + "#base", size, mass_of(size))
		else:
			# Studless: solid box, sockets all the way across the underside,
			# nothing on top.
			base = world.bake_faced_archetype(part + "#base", size, mass_of(size),
					PackedByteArray(), _fill(size.x * size.z, FACE_NONE),
					_fill(size.x * size.z, FACE_SOCKET))
		if base < 0:
			push_error("BrickPalette: '%s' failed to bake" % part)
			continue
		if is_bracket(part):
			world.set_side_studs(base, _side_studs_for(size))
		for name in variants_of(part):
			var o := orientation_of(name)
			var id := world.bake_variant(base, name, o.x, o.y != 0)
			if id < 0:
				push_error("BrickPalette: '%s' failed to orient" % name)
			out[name] = id
	return out


## A shaped part's base archetype: the cell mask, stud and socket masks, mass,
## surface and hulls all from one ShapedParts description. The variants that
## follow turn every one of them together.
static func _bake_shaped(world: BrickWorld, part: String, size: Vector3i) -> int:
	var spec: Dictionary = _SHAPED[part]
	var sh := ShapedParts.build(spec.kind, size, spec.get("axis", "z"))
	var up := PackedByteArray()
	var down := PackedByteArray()
	for i in size.x * size.z:
		up.append(FACE_STUD if sh.studs[i] != 0 else FACE_NONE)
		down.append(FACE_SOCKET if sh.sockets[i] != 0 else FACE_NONE)
	var id := world.bake_faced_archetype(part + "#base", size, sh.solid * MASS_PER_CELL,
			sh.cells, up, down)
	if id < 0:
		return -1
	world.set_archetype_mesh(id, sh.positions, sh.normals)
	world.set_archetype_hulls(id, sh.hulls)
	return id


## Face values, mirroring `brick::Face` in brick_types.h.
const FACE_NONE := 0
const FACE_STUD := 1
const FACE_SOCKET := 2


## Does this part carry studs on top in its canonical orientation? Everything
## but a tile and a curved slope does. (A slope has them only on its back
## strip, but it has them.)
static func has_studs(part: String) -> bool:
	return not part.begins_with("tile_") and not part.begins_with("curve_")


## Is this part a shape rather than a box?
static func is_shaped(part: String) -> bool:
	return _SHAPED.has(part)


## Does this part have a FRONT? A slope or a curve does: yawing it 180 degrees
## is a different part in the world, not the same one, so it has four
## orientations where a brick has two. Its names say which with `_y0`.. `_y3`,
## quarter turns about +Y from canonical.
##
## A bracket does too: its studs are on ONE side, so turned 180 degrees they
## face the other way. Given only `_x` / `_z` it could be turned two ways and
## never the other two.
static func is_directional(part: String) -> bool:
	return is_bracket(part) or (_SHAPED.has(part) and ((_SHAPED[part] as Dictionary).has("axis")
			or (_SHAPED[part] as Dictionary).has("front")))


## A bracket also carries studs on one lateral face.
static func is_bracket(part: String) -> bool:
	return part.begins_with("bracket_")


## Side studs down the part's LONG side (+X in the canonical W x H x L), one per
## stud of its length: a 1x4 bracket has four, in a row.
##
## One per column, not one per cell of the face. A brick is three plates tall
## and a stud is one stud wide, so a column holds exactly one real stud; the
## first version put one on every plate row -- three stacked half-overlapping
## studs a column -- and on the short END face, which is not where a bracket
## has them. Each is recorded on the TOP plate row, and really sits half a stud
## below the top, so a part built on it is flush with the bracket's top -- the
## real part's geometry, and the reason for it: flush with the BASE instead, a
## sideways part hangs down into the studs of whatever the bracket stands on.
## Recording the row rather than a height lets an inverted bracket carry it to
## the bottom row with everything else. The workshop draws and snaps to it.
##
## Six ints each: the cell they sit on, then the outward normal. The extension
## rotates both with the part, so every orientation of a bracket gets its studs
## facing the right way without any of this being written twice.
static func _side_studs_for(size: Vector3i) -> PackedInt32Array:
	var out := PackedInt32Array()
	var x := size.x - 1
	for z in size.z:
		# push_back one at a time: PackedInt32Array.append_array wants
		# another PackedInt32Array, and handing it an untyped Array
		# literal silently appends nothing.
		out.push_back(x)
		out.push_back(size.y - 1)
		out.push_back(z)
		out.push_back(1)
		out.push_back(0)
		out.push_back(0)
	return out


## The parts a player picks from. Build mode shows these, not archetypes.
static func parts() -> Array:
	return _PARTS.keys()


## Canonical footprint of a part, (W, H, L) with W <= L.
static func part_size(part: String) -> Vector3i:
	return _PARTS.get(part, Vector3i.ZERO)


## True when a part's footprint is square, so rotating it changes nothing.
static func is_square(part: String) -> bool:
	var s: Vector3i = _PARTS.get(part, Vector3i.ZERO)
	return s.x == s.z


## Archetype names for a part, in every orientation it has: the yaw variants
## (one if square, two if it only has a long axis, four if it has a front),
## each in upright and inverted form.
##
## `_x` is the orientation whose LONG side runs along world X; `_y1` is a
## directional part turned one quarter; `_i` is inverted.
static func variants_of(part: String) -> Array:
	if not _PARTS.has(part):
		return []
	var axes: Array
	if is_directional(part):
		axes = [part + "_y0", part + "_y1", part + "_y2", part + "_y3"]
	elif is_square(part):
		axes = [part]
	else:
		axes = [part + "_x", part + "_z"]
	var out := []
	for a in axes:
		out.append(a)
		out.append(a + "_i")
	return out


## The (yaw, flip) an archetype name asks for. yaw is quarter turns about +Y.
##
## The canonical part is long-on-Z, so `_z` is yaw 0 and `_x` is yaw 1.
static func orientation_of(name: String) -> Vector2i:
	var flip := 0
	var n := name
	if n.ends_with("_i"):
		flip = 1
		n = n.substr(0, n.length() - 2)
	var yaw := 0
	var tail := n.substr(n.length() - 3)
	if tail.begins_with("_y") and tail[2].is_valid_int():
		yaw = tail[2].to_int()
	elif n.ends_with("_x"):
		yaw = 1
	return Vector2i(yaw, flip)


## The archetype name for a part at quarter-turn `yaw` (any integer), upright or
## flipped. A part with only a long axis folds yaw 2 onto 0 and 3 onto 1; a
## square part has no yaw at all.
static func variant_name(part: String, yaw: int, flip: bool) -> String:
	var k := posmod(yaw, 4)
	var name: String
	if is_directional(part):
		name = "%s_y%d" % [part, k]
	elif is_square(part):
		name = part
	else:
		name = part + ("_x" if k % 2 == 1 else "_z")
	return name + ("_i" if flip else "")


## Which way a directional part's low front faces, as a unit grid vector, or
## ZERO for a part without one. The same quarter turn and flip bake_variant
## applies (Orient::direction), so this cannot disagree with the baked shape.
static func front_of(name: String) -> Vector3i:
	var part := part_of(name)
	if part == "" or not is_directional(part):
		return Vector3i.ZERO
	var v: Vector3i
	if is_bracket(part):
		v = Vector3i(1, 0, 0)  # the side its studs are on; see _side_studs_for
	elif (_SHAPED[part] as Dictionary).has("front"):
		v = _SHAPED[part].front
	else:
		v = Vector3i(0, 0, -1) if _SHAPED[part].axis == "z" else Vector3i(-1, 0, 0)
	var o := orientation_of(name)
	match o.x:
		1: v = Vector3i(-v.z, v.y, v.x)
		2: v = Vector3i(-v.x, v.y, -v.z)
		3: v = Vector3i(v.z, v.y, -v.x)
	if o.y != 0:
		v = Vector3i(v.x, -v.y, -v.z)
	return v


## The same part, turned one more quarter about +Y. What the workshop's rotate
## key does to a placed part; "" if the name is not the palette's.
static func turn(name: String) -> String:
	var part := part_of(name)
	if part == "":
		return ""
	var o := orientation_of(name)
	return variant_name(part, o.x + 1, o.y != 0)


## True when this archetype name is the inverted form of its part.
static func is_inverted(name: String) -> bool:
	return name.ends_with("_i")


## Every archetype name the palette bakes.
static func names() -> Array:
	var out := []
	for part in _PARTS:
		out.append_array(variants_of(part))
	return out


## Footprint of an ARCHETYPE, resolving the orientation suffix. Vector3i.ZERO
## if the name is not one the palette bakes.
##
## A flip leaves every extent unchanged (that is exactly why it is grid-legal),
## so only the axis suffix changes the size.
static func size_of(name: String) -> Vector3i:
	var n := name
	if n.ends_with("_i"):
		n = n.substr(0, n.length() - 2)
	if _PARTS.has(n):
		return _PARTS[n]  # square part, no axis suffix
	var cut := n.rfind("_")
	if cut < 0:
		return Vector3i.ZERO
	var part := n.substr(0, cut)
	var axis := n.substr(cut + 1)
	var s: Vector3i = _PARTS.get(part, Vector3i.ZERO)
	if s == Vector3i.ZERO:
		return Vector3i.ZERO
	if is_directional(part):
		# y0..y3; an odd quarter turn swaps the two stud axes.
		if axis.length() != 2 or axis[0] != "y" or not "0123".contains(axis[1]):
			return Vector3i.ZERO
		return Vector3i(s.z, s.y, s.x) if axis[1].to_int() % 2 == 1 else s
	if is_square(part) or not (axis == "x" or axis == "z"):
		return Vector3i.ZERO  # a square part must not carry an axis suffix
	# Canonical is long-on-Z. The _x variant swaps the two stud axes.
	return Vector3i(s.z, s.y, s.x) if axis == "x" else s


## The part a variant name belongs to, or "" if it is not one.
static func part_of(name: String) -> String:
	var n := name
	if n.ends_with("_i"):
		n = n.substr(0, n.length() - 2)
	if _PARTS.has(n):
		return n
	var cut := n.rfind("_")
	if cut < 0:
		return ""
	var part := n.substr(0, cut)
	return part if _PARTS.has(part) and size_of(name) != Vector3i.ZERO else ""


## Grams for a box part of this size, at print scale. A shaped part weighs its
## SOLID cells instead, which its bake counts: see `mass_of_part`.
static func mass_of(size: Vector3i) -> float:
	return size.x * size.y * size.z * MASS_PER_CELL


## Grams for a named part, box or shaped.
static func mass_of_part(part: String) -> float:
	if is_shaped(part):
		var spec: Dictionary = _SHAPED[part]
		return ShapedParts.build(spec.kind, part_size(part), spec.get("axis", "z")).solid \
				* MASS_PER_CELL
	return mass_of(part_size(part))


## What a part measures in metres in game. Purely derived -- here so a UI can
## show it without re-deriving the grid.
static func extents_m(size: Vector3i) -> Vector3:
	return Vector3(size.x * STUD_M, size.y * PLATE_M, size.z * STUD_M)


## What the same part measures in mm on the print bed, at 1:1 (spec section 3).
static func extents_mm(size: Vector3i) -> Vector3:
	return Vector3(size.x * STUD_MM, size.y * PLATE_MM, size.z * STUD_MM)


static func _fill(n: int, v: int) -> PackedByteArray:
	var a := PackedByteArray()
	a.resize(n)
	a.fill(v)
	return a
