extends SceneTree

## Writes Docs/Parts: one measurement sheet per part family, a profile drawing
## for every shaped part, and parts.json with the same numbers for scripts.
##
##     godot --headless --path . --script tools/part_sheets.gd
##
## GENERATED, never hand-edited. Every number comes from BrickPalette and
## ShapedParts -- the same code the game bakes its parts from -- so a sheet
## cannot say one thing while the game does another. Change a part, run this.
##
## Everything is in PRINT millimetres, which is also the Blender unit
## (Docs/Parts/README.md): one stud is 8.0 mm, one plate 3.2 mm. The game is the
## same thing x43.75, and each part says its game size too.

const OUT := "res://Docs/Parts/"
const SCALE := 43.75
## Real parts are 0.1 mm short of the grid on every side, so neighbours do not
## rub: a 1x1 is 7.8 mm across, not 8.0. The grid envelope is what the GAME
## uses; the real outline is what a printed or modelled part should be.
const CLEAR := 0.1
const STUD_D := 4.8
const STUD_H := 1.7
const TUBE_OD := 6.51
const TUBE_ID := 4.8

const FAMILIES := [
	["plate", "Plates", "One plate (3.2 mm) tall. Studs on top, sockets underneath."],
	["brick", "Bricks", "Three plates (9.6 mm) tall. Studs on top, sockets underneath."],
	["tile", "Tiles", "One plate tall with a SMOOTH top: sockets underneath, nothing on top."],
	["column", "Columns", "Eighteen plates (six bricks, 57.6 mm) tall: one storey of the city's frame."],
	["bracket", "Brackets", "A brick with studs down one long side, for building sideways."],
	["slope", "Slopes", "A brick whose top falls to the front; studs only on the flat back strip."],
	["curve", "Curved slopes", "A slope that bows outward; smooth all over, no studs."],
	["round", "Round bricks", "An octagonal brick, flats on the footprint edges."],
	["arch", "Arches", "Pillars at each end, a beam over an opening."],
	# One sheet, two families: the two windings are the same part mirrored.
	["spiral", "Spiral stairs", "A quarter turn of stair: a round-2x2 newel and two 45-degree steps. Clockwise (cw) or anticlockwise (ccw) seen from above.",
			["spiralcw", "spiralccw"]],
]

var _w: BrickWorld
var _p: Dictionary
var _json := {}


func _init() -> void:
	_w = BrickWorld.new()
	_p = BrickPalette.bake(_w)
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT + "profiles"))
	var index := PackedStringArray()
	for fam in FAMILIES:
		var prefixes: Array = fam[3] if fam.size() > 3 else [fam[0]]
		var parts := BrickPalette.parts().filter(func(p):
			return prefixes.any(func(pre): return p.begins_with(pre + "_")))
		if parts.is_empty():
			continue
		_write(OUT + fam[0] + "s.md", _family(fam, parts))
		index.append("| [%s](%ss.md) | %d | %s |" % [fam[1], fam[0], parts.size(), fam[2]])
	_write(OUT + "INDEX.md", "\n".join([
		"# Parts, by family",
		"",
		"Generated by `tools/part_sheets.gd` from the palette the game bakes. Do not edit;",
		"change the part and re-run. Conventions and anatomy: [README](README.md).",
		"",
		"| Family | Parts | What it is |",
		"|---|---|---|",
	] + Array(index)) + "\n")
	_write(OUT + "parts.json", JSON.stringify(_json, "  ", false) + "\n")
	print("part sheets: %d parts written to %s" % [_json.size(), OUT])
	quit(0)


func _write(path: String, text: String) -> void:
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string(text)
	f.close()


static func _mm(v: float) -> String:
	var s := "%.2f" % v
	while s.ends_with("0"):
		s = s.substr(0, s.length() - 1)
	return s.trim_suffix(".")


## The canonical variant: the one the part is authored in (W on X, L on Z).
func _canonical(part: String) -> String:
	return BrickPalette.variant_name(part, 0, false)


func _family(fam: Array, parts: Array) -> String:
	var out := PackedStringArray([
		"# %s" % fam[1], "",
		fam[2], "",
		"Generated by `tools/part_sheets.gd`. All sizes in **mm at print scale** (= Blender units,",
		"see [README](README.md)); game metres are x43.75. Origin is the part's min corner:",
		"X across the width W, Z along the length L, Y up. **Grid** is the envelope the game",
		"uses; **real** is the outline to model, %s mm in from the grid on every side." % _mm(CLEAR), "",
		"| Part | Studs W x L | Plates | Grid W x L x H | Real W x L x H | Game m | Studs | Mass g |",
		"|---|---|---|---|---|---|---|---|",
	])
	for part in parts:
		var s := BrickPalette.part_size(part)
		var gw := s.x * 8.0
		var gl := s.z * 8.0
		var gh := s.y * 3.2
		out.append("| `%s` | %d x %d | %d | %s x %s x %s | %s x %s x %s | %s x %s x %s | %d | %s |" % [
			part, s.x, s.z, s.y, _mm(gw), _mm(gl), _mm(gh),
			_mm(gw - 2 * CLEAR), _mm(gl - 2 * CLEAR), _mm(gh),
			_mm(gw * SCALE / 1000.0), _mm(gl * SCALE / 1000.0), _mm(gh * SCALE / 1000.0),
			_studs(part).size(), _mm(BrickPalette.mass_of_part(part))])
	out.append("")
	for part in parts:
		out.append_array(_detail(part))
	return "\n".join(out) + "\n"


## Stud centres on top, in mm, from the canonical archetype's up face.
func _studs(part: String) -> Array:
	var id: int = _p[_canonical(part)]
	var size := _w.get_archetype_size(id)
	var up: PackedByteArray = _w.get_archetype_up_face(id)
	var out := []
	for z in size.z:
		for x in size.x:
			if up[x + size.x * z] == BrickPalette.FACE_STUD:
				out.append(Vector2(4.0 + 8.0 * x, 4.0 + 8.0 * z))
	return out


## Underside: a tube where four socket cells meet, a pin between two in a
## one-wide part. Positions in mm.
func _underside(part: String) -> Dictionary:
	var id: int = _p[_canonical(part)]
	var size := _w.get_archetype_size(id)
	var dn: PackedByteArray = _w.get_archetype_down_face(id)
	var sock := func(x: int, z: int) -> bool:
		return x >= 0 and z >= 0 and x < size.x and z < size.z \
				and dn[x + size.x * z] == BrickPalette.FACE_SOCKET
	var tubes := []
	var pins := []
	var sockets := 0
	for z in size.z:
		for x in size.x:
			if sock.call(x, z):
				sockets += 1
	for z in range(1, size.z):
		for x in range(1, size.x):
			if sock.call(x - 1, z - 1) and sock.call(x, z - 1) and sock.call(x - 1, z) and sock.call(x, z):
				tubes.append(Vector2(8.0 * x, 8.0 * z))
	if size.x == 1:
		for z in range(1, size.z):
			if sock.call(0, z - 1) and sock.call(0, z):
				pins.append(Vector2(4.0, 8.0 * z))
	return {"tubes": tubes, "pins": pins, "sockets": sockets}


func _pts(a: Array) -> String:
	var s := PackedStringArray()
	for v in a:
		s.append("(%s, %s)" % [_mm(v.x), _mm(v.y)])
	return ", ".join(s) if not s.is_empty() else "none"


func _detail(part: String) -> PackedStringArray:
	var s := BrickPalette.part_size(part)
	var studs := _studs(part)
	var under := _underside(part)
	var out := PackedStringArray(["## `%s`" % part, ""])
	var rec := {
		"family": part.get_slice("_", 0),
		"studs_wl": [s.x, s.z], "plates": s.y,
		"grid_mm": [s.x * 8.0, s.y * 3.2, s.z * 8.0],
		"real_mm": [s.x * 8.0 - 2 * CLEAR, s.y * 3.2, s.z * 8.0 - 2 * CLEAR],
		"game_m": [s.x * 0.35, s.y * 0.14, s.z * 0.35],
		"mass_g": BrickPalette.mass_of_part(part),
		"studs_top_xz_mm": studs.map(func(v): return [v.x, v.y]),
		"tubes_xz_mm": under.tubes.map(func(v): return [v.x, v.y]),
		"pins_xz_mm": under.pins.map(func(v): return [v.x, v.y]),
		"variants": BrickPalette.variants_of(part),
	}
	out.append("- **Grid** %s x %s x %s mm; **real** %s x %s x %s mm; studs add %s mm on top." % [
		_mm(s.x * 8.0), _mm(s.z * 8.0), _mm(s.y * 3.2),
		_mm(s.x * 8.0 - 2 * CLEAR), _mm(s.z * 8.0 - 2 * CLEAR), _mm(s.y * 3.2), _mm(STUD_H)])
	out.append("- **Studs on top** (%d, Ø%s x %s mm, centres x, z): %s" % [
		studs.size(), _mm(STUD_D), _mm(STUD_H), _pts(studs)])
	if under.sockets > 0:
		out.append("- **Underside tubes** (Ø%s outer / Ø%s inner, centres x, z): %s" % [
			_mm(TUBE_OD), _mm(TUBE_ID), _pts(under.tubes)])
		if not under.pins.is_empty():
			out.append("- **Underside anti-stud pins** (one-wide part, between sockets; centres x, z): %s" % _pts(under.pins))
	else:
		out.append("- **Underside:** no sockets.")
	if BrickPalette.is_bracket(part):
		var side := []
		for z in s.z:
			side.append(Vector3(s.x * 8.0, s.y * 3.2 - 4.0, 4.0 + 8.0 * z))
		rec["side_studs_xyz_mm"] = side.map(func(v): return [v.x, v.y, v.z])
		out.append("- **Side studs** on the +X face (%d, centres x, y, z): %s" % [side.size(),
				", ".join(side.map(func(v): return "(%s, %s, %s)" % [_mm(v.x), _mm(v.y), _mm(v.z)]))])
		out.append("  - Centred half a stud (**4.0 mm**) below the top, so a part on them is flush with")
		out.append("    the bracket's top and one half plate (1.6 mm) above its base -- the real part's")
		out.append("    SNOT offset, exactly: centred in the top 5 of its 6 units. Same in game, in print")
		out.append("    and on a real bracket. See README.")
	if BrickPalette.is_shaped(part):
		out.append_array(_profile(part, rec))
	out.append("- **Orientations:** %s" % ", ".join(BrickPalette.variants_of(part)))
	out.append("")
	_json[part] = rec
	return out


## A shaped part's cross-section: the polygon, its plane and extrusion, in mm,
## and an SVG of it.
func _profile(part: String, rec: Dictionary) -> PackedStringArray:
	var spec: Dictionary = BrickPalette._SHAPED[part]
	var shape: Dictionary = ShapedParts._shape(spec.kind, BrickPalette.part_size(part),
			spec.get("axis", "z"))
	var out := PackedStringArray()
	var profiles := []
	for i in shape.draw.size():
		var pr: Dictionary = shape.draw[i]
		var k := 1000.0 / SCALE   # game metres -> print mm
		var poly := []
		for v in pr.poly:
			poly.append(Vector2(v.x * k, v.y * k))
		var axes: String = pr.plane
		var extrude := "xyz".replace(axes[0], "").replace(axes[1], "")
		# One drawing per piece; numbered when a part has more than one (a
		# spiral stair piece is a newel and two treads).
		var file := "profiles/%s.svg" % part if shape.draw.size() == 1 \
				else "profiles/%s_%d.svg" % [part, i]
		_write(OUT + file, _svg(part, poly, axes))
		profiles.append({"plane": axes, "extrude_axis": extrude,
				"extrude_mm": [pr.lo * k, pr.hi * k],
				"points_mm": poly.map(func(v): return [v.x, v.y])})
		out.append("- **Profile** in the %s plane (first number %s, second %s), extruded along %s from %s to %s mm:" % [
				axes.to_upper(), axes[0].to_upper(), axes[1].to_upper(), extrude.to_upper(),
				_mm(pr.lo * k), _mm(pr.hi * k)])
		out.append("  %s" % _pts(poly))
		out.append("")
		out.append("  ![%s profile](%s)" % [part, file])
		out.append("")
	rec["profiles"] = profiles
	return out


## The profile on a stud/plate grid, with its corner coordinates written on.
## White background and dark lines on purpose: it has to read in any viewer.
func _svg(part: String, poly: Array, axes: String) -> String:
	var px := 8.0                     # pixels per mm
	var pad := 60.0
	var maxv := Vector2.ZERO
	for v in poly:
		maxv = maxv.max(v)
	var w := maxv.x * px + pad * 2
	var h := maxv.y * px + pad * 2
	var tx := func(v: Vector2) -> Vector2:
		return Vector2(pad + v.x * px, h - pad - v.y * px)
	var s := PackedStringArray()
	s.append('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d" font-family="sans-serif" font-size="11">' % [w, h, w, h])
	s.append('<rect width="100%" height="100%" fill="#ffffff"/>')
	# Grid: studs (8 mm) on a horizontal stud axis, plates (3.2 mm) on Y.
	var step_x := 8.0
	var step_y := 3.2 if axes[1] == "y" else 8.0
	var x := 0.0
	while x <= maxv.x + 1e-3:
		var a: Vector2 = tx.call(Vector2(x, 0))
		var b: Vector2 = tx.call(Vector2(x, maxv.y))
		s.append('<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#d0d6e0"/>' % [a.x, a.y, b.x, b.y])
		x += step_x
	var y := 0.0
	while y <= maxv.y + 1e-3:
		var a: Vector2 = tx.call(Vector2(0, y))
		var b: Vector2 = tx.call(Vector2(maxv.x, y))
		s.append('<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="#d0d6e0"/>' % [a.x, a.y, b.x, b.y])
		y += step_y
	var pts := PackedStringArray()
	for v in poly:
		var q: Vector2 = tx.call(v)
		pts.append("%.1f,%.1f" % [q.x, q.y])
	s.append('<polygon points="%s" fill="#cfe3ff" stroke="#1f3b66" stroke-width="2"/>' % " ".join(pts))
	for v in poly:
		var q: Vector2 = tx.call(v)
		s.append('<circle cx="%.1f" cy="%.1f" r="2.5" fill="#1f3b66"/>' % [q.x, q.y])
		s.append('<text x="%.1f" y="%.1f" fill="#1f3b66">%s, %s</text>' % [q.x + 4, q.y - 4, _mm(v.x), _mm(v.y)])
	s.append('<text x="%.1f" y="18" fill="#333" font-size="13">%s -- %s plane, mm. grid: %s x %s mm</text>' % [
			pad, part, axes.to_upper(), _mm(step_x), _mm(step_y)])
	s.append('</svg>')
	return "\n".join(s) + "\n"
